server:
   port: 8090

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.179.116.147:3306/rent_car
       username: root
       password: carshare

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
